FROM centos
MAINTAINER duhaipeng <doosea@163.com>


#　复制并解压当前文件夹下的文件
ADD jdk-8u261-linux-x64.tar.gz /usr/local
ADD elasticsearch-6.1.3.tar.gz /home/

RUN mv /usr/local/jdk1.8.0_261 /usr/local/jdk \
    && mv /home/elasticsearch-6.1.3 /home/elasticsearch
#    && yum install -y nfs-utils

# 配置java 环境变量
ENV JAVA_HOME=/usr/local/jdk
ENV JRE_HOME=$JAVA_HOME/jre
ENV CLASSPATH=$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
ENV PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH

# 添加用户 和 用户组 es : es
RUN groupadd -r es && useradd -r -g es es

# 改变文件夹权限, 当前所有用户可读可写可执行
RUN chmod -R 777 /home/elasticsearch/

VOLUME ["/v1", "/v2", "/v3"]

EXPOSE 9200
EXPOSE 9300

USER es
WORKDIR /home/elasticsearch/bin
ENTRYPOINT [ "./elasticsearch" ]


# docker build -f ./Dockerfile_es  -t myes:1.0 .